---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Add user dista with password
    user:
      append: yes
      comment: Dista account
      generate_ssh_key: yes
      groups: sudo,video,audio,wheel,ssh
      name: dista
      shell: /bin/bash
      ssh_key_bits: 4096
