---
- hosts: localhost
  connection: local

  tasks:
  - name: Fetch updates
    ansible.builtin.apt:
      update_cache: yes
    become: true

  - name: Install updates
    ansible.builtin.apt:
      upgrade: dist
    become: true

  - name: Cleaning and autoremoving useless cache and packages
    ansible.builtin.apt:
      autoclean: yes
      autoremove: yes
    become: true

  - name: Installing libraries via apt
    ansible.builtin.apt:
      pkg:
      - ansible
      - aptitude
      - nano
      - python3
      - python3-apt
      - python3-pip
      - python3-setuptools
      - vim
      - virtualenv
    become: true

  - name: Installing libraries via pip3
    ansible.builtin.pip:
      executable: pip3
      name:
        - numpy
  
  - name: Make hidden Dista directory in the home directory
    ansible.builtin.file:
      path: "{{ansible_env.HOME}}/.dista/libraries/cuda"
      state: directory

  - name: Downloading Cuda (10.2)
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run
      dest: "{{ansible_env.HOME}}/.dista/libraries/cuda"
      mode: "755"

#  - name: Installing Cuda (10.2)
#    ansible.builtin.script: "{{ansible_env.HOME}}/.dista/libraries/cuda/cuda_10.2.89_440.33.01_linux.run"
#    args:
#      executable: /bin/sh

  - name: Downloading Cuda patch (1)
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/10.2/Prod/patches/1/cuda_10.2.1_linux.run
      dest: "{{ansible_env.HOME}}/.dista/libraries/cuda"
      mode: "755"

#  - name: Installing Cuda patch (1)
#    ansible.builtin.script: "{{ansible_env.HOME}}/.dista/libraries/cuda/cuda_10.2.1_linux.run"
#    args:
#      executable: /bin/sh

  - name: Downloading Cuda patch (2)
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/10.2/Prod/patches/2/cuda_10.2.2_linux.run
      dest: "{{ansible_env.HOME}}/.dista/libraries/cuda"
      mode: "755"

#  - name: Installing Cuda patch (2)
#    ansible.builtin.script: "{{ansible_env.HOME}}/.dista/libraries/cuda/cuda_10.2.2_linux.run"
#    args:
#      executable: /bin/sh

